### ISSUE TITLE
Support ignoring merge commits

### ISSUE THREAD

**Issue by pdalpra** [criteo/cookbook-release#29]
Hi,

First, thank you for that quite handy gem :ok_hand: 

Would you accept that cookbook-release supports an option to ignore merge commits during next version computation ?

As unless Github's default merge commit's message is modified before merging or commits are squashed, cookbook-release's current behaviour would always produce at least minor bump version as the merge's commit message doesn't match any of the defined patterns.

I'd be glad to provide a PR if you like.

**Comment by kamaradclimber** [comment]
Thanks for the idea! Since we use gerrit internally we don't have
encountered this issue but I'd be happy to have a look of you opened a PR.

Le ven. 9 déc. 2016 12:33, Pierre Dal-Pra <notifications@github.com> a
écrit :

**Comment by kamaradclimber** [comment]
fixed by #30
